name: Linux

on:
  pull_request:
  push:
  release:
    types: published

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        compiler: [gcc, clang]
        config: [Release, Debug]

    env:
      CC:  ${{ matrix.compiler == 'gcc' && 'gcc' || 'clang'   }}
      CXX: ${{ matrix.compiler == 'gcc' && 'g++' || 'clang++' }}
      CMAKE_C_COMPILER_LAUNCHER: ccache
      CMAKE_CXX_COMPILER_LAUNCHER: ccache

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 1
        submodules: recursive

    - uses: hendrikmuhs/ccache-action@v1
      with:
        key: linux-${{ matrix.compiler }}-${{ matrix.config }}

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt install -y iwyu clang clang-tidy clang-tools

    - name: Configure
      run: |
        cmake -B build -DLONGERON_BUILD_TESTS=ON -DLONGERON_BUILD_EXAMPLES=ON -DCMAKE_BUILD_TYPE=${{ matrix.config }} -DCMAKE_LINK_WHAT_YOU_USE=TRUE

    - name: Compile Unit Tests
      run: |
        cmake --build build --parallel --config ${{ matrix.config }}

    - name: Run Unit Tests
      run: |
        ctest --schedule-random --progress --output-on-failure --parallel --no-tests error --build-config ${{ matrix.config }} --test-dir build/test

